### PR TITLE
CRDCDH-1308

### PR DESCRIPTION
**Pull request by kuffelgr**
This is to support [CRDCDH-1234](https://tracker.nci.nih.gov/browse/CRDCDH-1234)

ICDC Data Model changes **are required** in order to support integration into the CRDC Data Hub (DH).

Changes Detailed Below:

icdc-model.yml

- Add version number
- Add crdc_id prop to all nodes
- Add file_id prop to file node for DCF guids supplied by Data Hub

icdc-model-props.yml

- Add template tag for crdc_id
- Change uuid, file_status, and file_location to "not required" since these values be generated by the DH in the future.

### CODE REVIEW

**Review by majensen — COMMENTED** [review]
Will the data hub really create a CRDC ID for all these entities? I thought it was basically patient, sample, and file.

**Comment by majensen** [comment]
> Will the data hub really create a CRDC ID for all these entities? I thought it was basically patient, sample, and file.

Another way of framing this question: is there an explicit document from DH specifying the nodes for which they will create common ids?

**Comment by kuffelgr** [comment]
> > Will the data hub really create a CRDC ID for all these entities? I thought it was basically patient, sample, and file.
> 
> Another way of framing this question: is there an explicit document from DH specifying the nodes for which they will create common ids?

I'm not sure @majensen . The instructions in the ticket I am working on required crdc_id to be added to all nodes.
https://tracker.nci.nih.gov/browse/CRDCDH-1308

**Review by majensen — APPROVED** [review]
I'm ok with this, since these extra ids won't hurt anything. But we should continue to try to resolve this question with Ming.

**Pull request merged**
